[profile.default]
src = 'src'
test = 'tests'
script = 'scripts'
out = 'out'
libs = ['lib']
remappings = [
]
fs_permissions = [{access = "write", path = "./reports"}]

[rpc_endpoints]
rollux = "https://rpc.rollux.com/"

[etherscan]
rollux = { chain_id = 570, key = "abc", url = "https://explorer.rollux.com/api" }

# See more config options https://github.com/gakonst/foundry/tree/master/config
