[profile.default]
src = 'src'
test = 'tests'
script = 'scripts'
out = 'out'
libs = ['lib']
remappings = [
]
fs_permissions = [{access = "write", path = "./reports"}]

[rpc_endpoints]
rollux = "https://rpc1.rollux.com/"

[etherscan]
rollux={key="abc",chainId=570}

# See more config options https://github.com/gakonst/foundry/tree/master/config
